name: test_gpu
on: [push]
jobs:
  run:
    runs-on: [self-hosted, server]    
    steps:
        uses: actions/checkout@v3
        run: |
          ls ${{ github.workspace }}
        run: docker build -t home_api .
