name: main
on: [push]
jobs:
  run:
    runs-on: [self-hosted, server]    
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
          #- run: docker stop home-api
          #      - run: docker rm home-api
          #      - run: docker rmi home-api
      - run: docker build -t home-api .
      - run: docker run -d --publish 5000:5000 --restart unless-stopped --name home_api home-api
