name: main
on: [push]
jobs:
  name: Testing this1
  run:
    runs-on: [self-hosted, server]    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        env:
          SECRET: ${{ secrets.HOME_API_SQL_PASSWORD }}
      - run: ./gen_cred.sh ${{ vars.HOME_API_SQL_DB }} ${{ vars.HOME_API_SQL_USER }} ${{ vars.HOME_API_SQL_HOST }} ${{secrets.HOME_API_SQL_PASSWORD}}
      - run: cat src/cred.py
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: docker stop home_api
      - run: docker rm home_api
      - run: docker rmi home-api
      - run: docker build -t home-api .
      - run: docker run -d --publish 5000:5000 --restart unless-stopped --name home_api home-api
   name: Do testing if everything works
   run: 
     runs-on: [self-hosted, server]
     steps:
       - name: testing more
       - run: python3 src/test.py
