name: main
on: [push]
jobs:
  run:
    runs-on: [self-hosted, server]    
    steps:
      env:
        SECRET: ${{ secrets.HOME_API_SQL_PASSWORD }}
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo DATABASE=\"${{ vars.HOME_API_SQL_DB }}\" > src/cred.py
      - run: echo SQL_UW=\"${{ vars.HOME_API_SQL_USER }}\" >> src/cred.py
      - run: echo HOST=\"${{ vars.HOME_API_SQL_HOST }}\" >> src/cred.py
      - run: echo PASSWORD=\"$SECRET\" >> src/cred.py
      - run: cat src/cred.py
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: docker stop home_api
      - run: docker rm home_api
      - run: docker rmi home-api
      - run: docker build -t home-api .
      - run: docker run -d --publish 5000:5000 --restart unless-stopped --name home_api home-api
