name: Experiment
on: [push]

#jobs:
#  job1:
#    name: Stopping containers
#    runs-on: [self-hosted, server]
#    steps:
#      - name: Stop container home-api
#      - run: docker stop home_api
#      - run: docker rm home_api
#      - run: docker rmi home_api

  job2:
    name: Welding container
    runs-on: [self-hosted, server]
    steps:
    - name: Checking out repo
      uses: actions/checkout@v3
      env:
        SECRET: ${{secrets.HOME_API_SQL_PASSWORD}}
    - run: ./gen_cred.sh ${{ vars.HOME_API_SQL_DB }} ${{ vars.HOME_API_SQL_USER }} ${{ vars.HOME_API_SQL_HOST }} ${{secrets.HOME_API_SQL_PASSWORD}}
    - run docker build -t home-api .

      #  job3:
    #    name: Starting container
    #    needs: job2
    #    runs-on: [self-hosted, server]
    #    steps:
    #    - name: Placing container
    # run: docker run -d --publish 5000:5000 --restart unless-stopped --name home_api home-api
      #      
      #  job4:
      #    name: Testing container
      #    needs: job3
      #    runs-on: [self-hosted, server]
      #    steps:
      #    - name: Testing!
      #      run: python3 src/test.py
